/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData facebook = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guia = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recomendacion = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData principal = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saturacion = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salir = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nose = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consideraciones = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacto = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correo = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ejercicios = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
